dumplimgs/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
# from django.template.context_processors import static
from django.urls import path, include

from restasite import views

urlpatterns = [
                  # path('pelmeni', views.pelmeni, name='pelmeni'),
                  # path('pelmeni/<str:category>', views.pelmeni, name='pelmeni'),
                  # path('pelmennaia', views.pelmennaia, name='pelmennaia'),
                  # path('', views.index, name='index'),
                  # path('contact', views.contact, name='contact'),
                  path('', include('restasite.urls')),
                  path('admin/', admin.site.urls),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL,
                       document_root=settings.MEDIA_ROOT)

restasite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from restasite import views

app_name = 'restasite'
urlpatterns = [
              path('', views.index, name='index'),
              path('pelmeni', views.pelmeni, name='pelmeni'),
              path('pelmeni/<str:category>', views.pelmeni, name='pelmeni'),
              path('pelmennaia', views.pelmennaia, name='pelmennaia'),
              path('contact', views.contact, name='contact'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL,
              document_root=settings.MEDIA_ROOT)

restasite/models.py
from django.db import models

# Create your models here.
class menu_item(models.Model):
    #текст метки - verbose_name
    title = models.CharField(max_length=70, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='images', verbose_name='Изображение')
    price = models.DecimalField(max_digits=10,decimal_places=2,verbose_name='Цена')

    TYPE = {
        ('CHI', 'Куриные'),
        ('BEF', 'Говяжьи'),
        ('VEG', 'Веганские')
    }
    type=models.CharField(choices=TYPE,max_length=3,default='NEW',verbose_name='Тип')

    def __str__(self):
        return self.title

restasite/forms.py
from django import forms


class contact_form(forms.Form):
    name = forms.CharField(
        min_length=2,
        widget=forms.TextInput(
            attrs={'placeholder':'Ваше имя'}
        )
    )
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'placeholder': 'Ваш email'}
        )
    )
    message = forms.CharField(
        min_length =20,
        widget=forms.Textarea(
            attrs={'placeholder': 'Сообщение'}
        )
    )

restasite/views.py
from django.core.mail import EmailMultiAlternatives
from django.shortcuts import render
from django.template.loader import get_template

from restasite.forms import contact_form
from restasite.models import menu_item
# Create your views here.

def pelmeni(request, category=None):
    # menu_chi = menu_item.objects.filter(type__exact='CHI').order_by('?')[:6]
    # menu_bef = menu_item.objects.filter(type__exact='BEF').order_by('?')[:6]
    # menu_veg = menu_item.objects.filter(type__exact='VEG').order_by('?')[:6]

    menu = menu_item.objects.all().order_by('type')

    if category:
        menu = menu_item.objects.filter(type__exact=category)

    print(menu)

    # словарь фильтров
    context = {
        # 'menu_chi': menu_chi,
        # 'menu_bef': menu_bef,
        # 'menu_veg': menu_veg,
        'menu': menu
    }
    return render(
        request,
        'pelmeni.html',
        context=context
    )

def pelmennaia(request):
    return render(
        request,
        'pelmennaia.html'
    )
def index(request):
    return render(
        request,
        'index.html'
    )
def contact(request):
    context={}
    if request.method=='POST':
        form = contact_form(request.POST)
        # проверка корректности полей формы
        if form.is_valid():
            send_message(
                form.cleaned_data['name'],
                form.cleaned_data['email'],
                form.cleaned_data['message']
            )
            context={'success': 1}
    else:
        form = contact_form()
    context['form'] = form
    return render(
        request,
        'contact.html',
        context=context
    )

def send_message(name,email,message):
    text=get_template('message.html')
    html=get_template('message.html')
    context = {
        'name':name, 'email':email,'message':message
    }
    #тема для письма
    subject='Сообщение от пользователя'
    from_email='from@example.com'
    text_content=text.render(context)
    html_content = text.render(context)

    msg=EmailMultiAlternatives(subject,text_content,from_email, ['manager@example.com'])
    # добавление альтернативной версии
    msg.attach_alternative(html_content,'text/html')
    msg.send()

restasite/templates/contact.html
{% extends 'main.html' %}
{% block title %}<title>Контакты</title>{% endblock %}
{% load static %}
{% block content %}
<div class="slider">
    <div class="slider_block">
        <div class="slaider_text">
           <p>ОСТАВИТЬ<br>ОТЗЫВ</p>
        </div>
        <div class="slaider_button">
            <div class="_button">
                <div class="_button_text">НАПИСАТЬ</div>
            </div>
        </div>
    </div>
    <div class="container">
       <span class="slide"><img src="{% static 'img/slider.png'%}"/></span>
       <span class="slide"><img src="{% static 'img/place1.png'%}"/></span>
       <span class="slide"><img src="{% static 'img/place2.png'%}"/></span>
    <div class="next"><span><img src="{% static 'img/right.png'%}"></span></div>
    <div class="prev"><span><img src="{% static 'img/left.png'%}"></span></div>
    </div>
</div>

<div class="main_catalog">
    <div class="catalog">
        <p class="catalog__title">СВЯЖИТЕСЬ С НАМИ</p>
        <form class="connect" method="post" action="">
            <!--устранение ошибки 403-->
            {%csrf_token%}
            {%if success %}
                <div class="alert_info">
                    <h1>✓ Спасибо за сообщение!</h1>
                </div>
            {%else%}
                {%if form.message.errors %}
                    <div class="errors">
                        <strong>form.message.errors</strong>
                    </div>
                {%endif%}
                {{form.message}}
                {%if form.name.errors %}
                    <div class="errors">
                        <strong>form.name.errors</strong>
                    </div>
                {%endif%}
                {{form.name}}
                {%if form.email.errors %}
                    <div class="errors">
                        <strong>form.email.errors</strong>
                    </div>
                {%endif%}
                {{form.email}}
                <input type="submit" value="Отправить" id="send">
            {% endif %}
        </form>
    </div>
</div>
<style>
.slaider{
    background-image: URL(img/slider.png);
    background-size: 100%;
    width: 100%;
    height: 500px;
    background-repeat: no-repeat;
    font-size: 20px;
    display: flex;
    justify-content: space-around;
    text-align: start;
    align-items: center;
}
.slaider img{
    width: 100%;
}
.slider_block{
    width: 415px;
    height: 255px;
    position: absolute;
    left: 40%;
    top: 90px;
}
.slaider_text {
    font-weight: 600;
    font-size: 70px;
    line-height: 82px;
    letter-spacing: 0.04em;
    margin-bottom: 25px;
}
.body{
text-align: center;
}
.slider{
    position: relative;
    width:100%;
    margin-left: auto;
    margin-right:auto;
    overflow: hidden;
    white-space:nowrap;
    cursor:default;
}
.container{
    width:100%;
    font-size:0;
}
.slide{
    display:inline-block;
    width:100%;
}
.slide img{
    width:100%;
}
.next{
    display:table;
    position:absolute;
    left:88%;
    top:43%;
    width:10%;
    height:90px;
}
span{
    display:table-cell;
    vertical-align: middle;
    color:rgb(255,255,255);
    font-size:60px;
    font-weight:900;
}
span:hover{
    color:rgb(167,167,167);
    cursor: pointer;
}
.prev{
    display:table;
    position: absolute;
    left:4%;
    top:43%;
    width:10%;
    height:90px;
}
.connect{
    align-items: center;
    text-align: start;
    display: flex;
    flex-direction: column;
    justify-content: center;
    padding-bottom: 100px;
}
.connect input, .connect textarea{
    background-color: #F5F5F5;
    border: 1px solid #131515;
    height: 60px;
    width: 500px;
    box-sizing: border-box;
    margin-bottom: 15px;
}

.connect input::placeholder, .connect textarea::placeholder{
    padding-left: 20px;
    font-size: 18px;
}

#send {
    display: inline-block;
    padding: 15px 20px;
    background-color: #131515;
    color: #F5F5F5;
    text-align: center;
}
    #send ::placeholder{
        font-weight: 500;
        font-size: 30px;
        line-height: 35px;
        letter-spacing: 0.04em;
    }
</style>
{% endblock %}

restasite/templates/index.html
{% extends 'main.html' %}
{% block title %}<title>Главная</title>{% endblock %}
{% load static %}
{% block header %}
<header class="header wrapper_b ">
    <div class="logo">
        <a href="{% url 'restasite:index' %}">
            <img src="{% static 'img/logo_white.png'%}">
        </a>
    </div>
    <div class="nav _w">
        <a href="{% url 'restasite:index' %}">О НАС</a>
        <a href="{% url 'restasite:pelmeni' %}">ПЕЛЬМЕНИ</a>
        <a href="{% url 'restasite:pelmennaia' %}">ПЕЛЬМЕННЫЕ</a>
        <a href="{% url 'restasite:contact' %}">ОТЗЫВЫ</a>
    </div>
    <div class="contact">
        <img src="{% static 'img/vk_white.png'%}">
        <img src="{% static 'img/tg_white.png'%}">
    </div>
</header>
{% endblock %}
{% block content %}
    <div class="main_content__image">
        <div class="image_block">
            <div class="image_text">
                <p>ДОБРО<br>ПОЖАЛОВАТЬ<br> <span>НА «ПЛАНЕТУ ПЕЛЬМЕНЕЙ»</span> </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

restasite/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}<title>Пельмени</title>{% endblock %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css'%}">
</head>
<body>
<div class="wrapper">
    {% block header %}
        <header class="header">
            <div class="logo">
                <a href="{% url 'restasite:index' %}">
                    <img src="{% static 'img/logo.png'%}">
                </a>
            </div>
            <div class="nav _b">
                <a href="{% url 'restasite:index' %}">О НАС</a>
                <a href="{% url 'restasite:pelmeni' %}">ПЕЛЬМЕНИ</a>
                <a href="{% url 'restasite:pelmennaia' %}">ПЕЛЬМЕННЫЕ</a>
                <a href="{% url 'restasite:contact' %}">ОТЗЫВЫ</a>
            </div>
            <div class="contact">
                <img src="{% static 'img/vk_black.png'%}">
                <img src="{% static 'img/tg_black.png'%}">
            </div>
        </header>
    {% endblock %}
        <div class="main">
            <div class="main_content">
                {% block content %} {% endblock %}
            </div>
        </div>
        <footer class="footer">
            <div class="footer_content">
                <div class="logo">
                    <img src="{% static 'img/logo_white.png'%}">
                </div>
                <div class="footer_nav">
                    <div class="footer_nav__item">
                        <a href="#">О НАС</a>
                        <a href="#">ДОСТАВКА</a>
                    </div>
                    <div class="footer_nav__item">
                        <a href="{% url 'restasite:index' %}">ПЕЛЬМЕНИ</a>
                        <a href="#">ПЕЛЬМЕННЫЕ</a>
                    </div>
                    <div class="footer_nav__item">
                        <a href="#">УСЛОВИЯ ИСПОЛЬЗОВАНИЯ САЙТА</a>
                        <a href="#">ПОЛИТИКА ОБРАБОТКИ ПЕРСОНАЛЬНЫХ ДАННЫХ</a>
                        <a href="#">УСЛОВИЯ ЗАКАЗА И ДОСТАВКИ</a>
                    </div>
                </div>
                <div class="contact">
                    <img src="{% static 'img/vk_white.png'%}">
                    <img src="{% static 'img/tg_white.png'%}">
                </div>
            </div>
        </footer>
    </div>
</body>
    <script src="{% static 'js/jquery-3.3.1.min.js'%}"></script>
    <script src="{% static 'js/main.js'%}"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;700&family=Raleway:wght@300;400;600;700&display=swap" rel="stylesheet">
</html>

restasite/templates/message.html
Здравствуйте!

Новое сообщение от пользователя сайта "Планета пельменей".
Имя: {{name}}
Почта: {{email}}
Сообщение: {{message}}

restasite/templates/pelmeni.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
    <div class="filter__pel">
        <div class="title__pel">
            <p>ПЕЛЬМЕНИ</p>
        </div>
        <nav class="filter">
            <ul>
                <li data-f="ALL">
                    <a href="{% url 'restasite:pelmeni' %}"><b>Все виды</b></a>
                </li>
                <li data-f="CHI" class="text_CHI">
                    <a href="{% url 'restasite:pelmeni' category='CHI' %}">Куриные </a>
                </li>
                <li data-f="BEF" class="text_BEF">
                   <a  href="{% url 'restasite:pelmeni' category='BEF' %}">Говяжьи </a>
                </li>
                <li data-f="VEG" class="text_VEG">
                    <a href="{% url 'restasite:pelmeni' category='VEG' %}">Веганские </a>
                </li>
            </ul>
        </nav>
    </div>
    <div class="main_catalog">
        <div class="catalog_pelmenei">
            {% for item in menu %}
                <div class="box {{ item.type }}">
                    <div class="card__img_pel">
                        <img src="{{ item.image.url }}" alt="{{ item.title }}">
                    </div>
                    <div class="card__name text_CHI">{{ item.title }}</div>
                    <div class="card__text">{{ item.description }}</div>
                    <div class="card__button">
                        <div class="button">
                            <div class="button_text">В КОРЗИНУ</div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

restasite/templates/pelmennaia.html
{% extends 'main.html' %}
{% block title %}<title>Пельменная</title>{% endblock %}
{% load static %}
{% block header %}
<header class="header wrapper_b ">
    <div class="logo">
        <a href="{% url 'restasite:index' %}">
            <img src="{% static 'img/logo_white.png'%}">
        </a>
    </div>
    <div class="nav _w">
        <a href="{% url 'restasite:index' %}">О НАС</a>
        <a href="{% url 'restasite:pelmeni' %}">ПЕЛЬМЕНИ</a>
        <a href="{% url 'restasite:pelmennaia' %}">ПЕЛЬМЕННЫЕ</a>
        <a href="{% url 'restasite:contact' %}">ОТЗЫВЫ</a>
    </div>
    <div class="contact">
        <img src="{% static 'img/vk_white.png'%}">
        <img src="{% static 'img/tg_white.png'%}">
    </div>
</header>
{% endblock %}
{% block content %}
<div class="catalog wrapper_b _w">
    <p class="catalog__title">ПЕЛЬМЕННЫЕ</p>
    <div class="map">
        <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A18ecf8a6a9c643c32e920a1f6c74da7f6791eb5610f89854aabb6d080366d916&amp;width=800&amp;height=470&amp;lang=ru_RU&amp;scroll=true"></script>
    </div>
    <div class="place">
        <div class="card__name">
            ПЕЛЬМЕННЫЙ БУТИК
        </div>
        <div class="card__text">
            Москва, Столешников пер., д. 9, стр. 1<br>
            пн-вс 10:00 — 23:00<br>
            +7 (969) 347-35-24<br>
        </div>
    </div>
    <div class="place">
        <div class="card__name">
            ПЕЛЬМЕННАЯ В САДУ
        </div>
        <div class="card__text">
            Москва, Столешников пер., д. 26, стр. 1<br>
            пн-вс 10:00 — 23:00<br>
            +7 (969) 347-35-23<br>
        </div>
    </div>
    <div class="place">
        <div class="card__name">
            ПЕЛЬМЕННАЯ НА ЗАВОДЕ
        </div>
        <div class="card__text">
            Москва, ул. Ленинская Слобода, д. 26, strEAT in Roomer<br>
            пн-вс 10:00 — 23:00<br>
            +7 (985) 481-42-49<br>
        </div>
    </div>
    <div class="place">
        <div class="card__name">
            ПЕЛЬМЕННАЯ НА РЫНКЕ
        </div>
        <div class="card__text">
            Москва, ул. Мытная, д. 74, Даниловский рынок<br>
            пн-вс 10:00 — 23:00<br>
            +7 (499) 399-31-23<br>
        </div>
    </div>
    <div class="place">
        <div class="card__name">
            НОВАЯ ПЕЛЬМЕННАЯ В СТАРОМ ГОРОДЕ
        </div>
        <div class="card__text">
            Москва, ул. Маросейка, д. 9/2, стр. 1<br>
            круглосуточно<br>
            +7 (926) 424-40-22<br>
        </div>
    </div>
</div>
{% endblock %}